apiVersion: v1
kind: ConfigMap
metadata:
  name: literal-config
data:
  name: "lay"
  password: "123456"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  log_level: "info"
---
apiVersion: v1
kind: Pod
metadata:
  name: literal-config-pod
  labels:
    role: literal-config-pod
spec:
  containers:
    - name: literal-config-pod
      image: wangyanglinux/myapp:v1.0
      command:
        - /bin/sh
        - -c
        - env
      env:
        - name: name
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: name
        - name: password
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: password
      envFrom:
        - configMapRef:
            name: env-config
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: Never
